### ISSUE TITLE
not able to use for multiple components

### ISSUE THREAD

**Issue by pmalikbtech** [tnicola/ngx-joyride#3]
i am using this for my angular2 application. and code for joyride is in app componet.ts/app.component.html. but i have 3 components where i want to show the tour(sidebar component, header component and dashboard component). is it possible that it will be work for all over application.

**Comment by tnicola** [comment]
Hi @pmalikbtech! Yes, it's possible. The code you see it's just a simple demo for showing you how the library works. You can use the directive wherever you'd like to, in your header, sidebar and dashboard. Just use the joyrideStep directive inside your components, then you can inject the JoyrideService in any component, even a different one, in the end start the tour. 

e.g.:

sidebar.component.ts
```
@Component({
    selector: 'sidebar',
    template: '<div joyrideStep title="The sidebar" text="..." stepNumber="1"></div>'
})
```

header.component.ts
```
@Component({
    selector: 'header',
    template: '<div joyrideStep title="The header" text="..." stepNumber="2"></div>'
})
```
app.component.ts
```
@Component({
  selector: 'app-component',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass'],
})
export class AppComponent {
  constructor(private readonly joyrideService: JoyrideService) { }

  onClick() {
    this.joyrideService.startTour();
  }
}

```
Let me know if you need any help. 😄

**Comment by olegsh7** [comment]
This is not working. It add new steps in steps and stepsOrignal arrays every time then component is open. Just create two different components and route betwen them

**Comment by tnicola** [comment]
@olegsh7 Do you have a more detailed example? 

When you say "route" you mean using the Angular Router, right? Because at the moment the Joyride cannot navigate among pages. Anyway, this feature it's on the roadmap.

**Comment by olegsh7** [comment]
Yes, I am mean angular router. Thank you

**Comment by tnicola** [comment]
Page routing is now available in ngx-joyride@2.0.0 . Check the Readme:  [Multi pages navigation](https://github.com/tnicola/ngx-joyride#how-to-get-multi-pages-joyride-navigation-available-from-v200) .

**Comment by olegsh7** [comment]
Thank you. Unfortunately, new version not working at all in my Angular 5 project:

Uncaught (in promise): TypeError: undefined is not a function
TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at webpackAsyncContext (eval at ./src/$$_lazy_route_resource lazy recursive (http://localhost:4200/main.bundle.js:20:1), <anonymous>:82:34)
    at SystemJsNgModuleLoader.loadAndCompile (webpack-internal:///./node_modules/@angular/core/esm5/core.js:6756:82)
    at SystemJsNgModuleLoader.load (webpack-internal:///./node_modules/@angular/core/esm5/core.js:6740:60)
    at RouterConfigLoader.loadModuleFactory (webpack-internal:///./node_modules/@angular/router/esm5/router.js:4626:122)
    at RouterConfigLoader.load (webpack-internal:///./node_modules/@angular/router/esm5/router.js:4606:52)
    at MergeMapSubscriber.eval [as project] (webpack-internal:///./node_modules/@angular/router/esm5/router.js:2098:115)
    at MergeMapSubscriber._tryNext (webpack-internal:///./node_modules/rxjs/_esm5/operators/mergeMap.js:133:27)
    at MergeMapSubscriber._next (webpack-internal:///./node_modules/rxjs/_esm5/operators/mergeMap.js:123:18)
    at MergeMapSubscriber.Subscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:96:18)

**Comment by tnicola** [comment]
Oh, I'm sorry. Are you using `@angular/cli`? If so, which version?
Did you notice this issue after upgrading the library to 2.0.0 or have you added/upgraded something else?

Because it doesn't seem strictly related to ngx-joyride. I've found a couple of similar issues on @angular/cli:
- https://github.com/angular/angular-cli/issues/9651
- https://github.com/angular/angular-cli/issues/9775

Solutions could be:

- If you're using angular/cli, try to update to 1.7.2 version
- If you're using lazy loaded modules, check that you're not also importing them

**Comment by olegsh7** [comment]
version of cli is 1.7.0. But I am cannot just change cli version and/or lazy loading of modules, it is big project with many peoples involved. But thank you any way, you do great job with this control

**Comment by tnicola** [comment]
Ok, I understand. Thank you! Anyway it should be a problem with `@angular/cli` and lazy loaded modules. I've found another solution tested on other projects, the one suggested here: https://github.com/angular/angular-cli/issues/9825#issuecomment-372094115 . Try to change:

{ path: 'my/route', loadChildren: './path/my-lazy-loaded.module#MyLazyLoadedModule' },

to

{ path: 'my/route', loadChildren: () => MyLazyLoadedModule }
